name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn install --immutable

  ESLint:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn ci:lint:eslint

  Prettier:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn ci:lint:prettier

  Build:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn build

  E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn ci:e2e
